version: 2.1
#orbs:
#  terraform: circleci/terraform@3.2.0
workflows:
  default:
    jobs:
      - deploy_main:
          context:
            - main

jobs:
  deploy_main:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - deploy_stack

commands:
  deploy_stack:
    description: Deploys the stack to main GCP account
    steps:
      - run:
          name: Save GCP Credentials
          command: echo "${main_sa_key}" > ./sa_credentials.json
      - run:
          name: Init Backend
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=./sa_credentials.json
            terraform init \
              -backend-config="bucket=yampy-main-tf-state" \
              -backend-config="prefix=gcp-account-projects"
      - run:
          name: Validate
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=./sa_credentials.json
            terraform validate
      - run:
          name: Validate
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=./sa_credentials.json
            terraform plan \
            --auto-approve
      - run:
          name: Apply
          command: |
            export GOOGLE_APPLICATION_CREDENTIALS=./sa_credentials.json
            terraform apply \
            --auto-approve